### ISSUE TITLE
Plugin Registration Plugin fails with XrmToolBox v1.2016.02.28

### ISSUE THREAD

**Issue by mscottsewell** [in-team/PluginRegistration#3]
The Plugin Registration Plugin - - now fails with XrmToolBox v1.2016.02.28
Apparently due to version change in the McTools.McTools.Xrm.Connection.

************** Exception Text **************
 System.IO.FileNotFoundException: Could not load file or assembly 'McTools.Xrm.Connection, Version=1.0.3315.606, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
 File name: 'McTools.Xrm.Connection, Version=1.0.3315.606, Culture=neutral, PublicKeyToken=null'
 at PluginRegistrationTool.MainControl.b__0(DoWorkEventArgs a)
 at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
 at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by macacq** [comment]
@mscottsewell can you test most recent release. It should run smoothly with newest version of XrmToolBox.

**Comment by mscottsewell** [comment]
Thanks - Tested it and it works great. - Much appreciated.
