### ISSUE TITLE
Request - add a "Close Tab" button to the plugin.

### ISSUE THREAD

**Issue by mscottsewell** [in-team/PluginRegistration#4]
The plugin registration plugin can't be closed once opened - you have to close the XrmToolBox completely in order to close the tab. - 
Not a showstopper of course, but would be nice to have.
Thanks!

**Comment by daryllabar** [comment]
You can always middle click on the plugin tab

**Comment by macacq** [comment]
`Ctrl+F4` also works, but I have implemented close button — it's a shame that I missed it previously.
